"use client";

import { useEffect, useState } from "react";

declare global { interface Window { Telegram?: { WebApp?: any }; Adsgram?: any } }

type Role="worker"|"client"|"admin";
type Tab="home"|"tasks"|"my"|"invite"|"wallet"|"post"|"posts"|"deposits"|"notifications"|"admin";
const money=(v:any)=>`${Number(v||0).toFixed(2)} ETB`;
const api=async(action:string,body:any={})=>{const initData=window.Telegram?.WebApp?.initData||"";const ref=new URLSearchParams(window.location.search).get("ref")||"";const r=await fetch(`/api/${action}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,initData,ref})});const d=await r.json().catch(()=>({error:"Server returned invalid response"}));if(!r.ok)throw new Error(d.error||"حدث خطأ");return d};

export default function App(){
 const [me,setMe]=useState<any>(null),[role,setRole]=useState<Role>("worker"),[tab,setTab]=useState<Tab>("home"),[data,setData]=useState<any>({}),[err,setErr]=useState(""),[busy,setBusy]=useState(false);
 async function loadMe(){try{const x=await api("me");setMe(x.user);setRole(x.user.is_admin?"admin":x.user.active_role||"worker")}catch(e:any){setErr(e.message)}}
 async function load(t=tab){setBusy(true);setErr("");try{const x=t==="home"?await api("dashboard",{role}):t==="tasks"?await api("tasks"):t==="my"?await api("my-tasks"):t==="invite"?await api("referrals"):t==="wallet"?await api("wallet"):t==="posts"?await api("my-posts"):t==="deposits"?await api("deposits"):t==="notifications"?await api("notifications"):t==="admin"?await api("admin-dashboard"):{};setData(x)}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 useEffect(()=>{window.Telegram?.WebApp?.ready?.();window.Telegram?.WebApp?.expand?.();loadMe()},[]); useEffect(()=>{if(me)load(tab)},[tab,role,me]);
 if(!me)return <main className="shell"><div className="card center splash"><div className="logo">S</div><h1>SERA TIME</h1><p>جاري تحميل حسابك...</p>{err&&<div className="alert">{err}</div>}</div></main>;
 const isAdmin=!!me.is_admin;
 const nav: [Tab,string][] = role==="client"?[['home','الرئيسية'],['post','نشر عمل'],['posts','أعمالي'],['deposits','إيداع'],['wallet','المحفظة']]:[['home','الرئيسية'],['tasks','الأعمال'],['my','مهامي'],['invite','دعوة'],['wallet','المحفظة']];
 if(isAdmin)nav.push(['admin','الإدارة']);
 return <main className="shell"><header className="topbar"><div className="brand"><div className="miniLogo">S</div><div><b>SERA TIME</b><small>WATCH • WORK • EARN</small></div></div><div className="topActions"><button className="icon" onClick={()=>setTab('notifications')}>🔔</button><button className="switch" onClick={async()=>{const r=role==='worker'?'client':'worker';try{await api('set-role',{role:r});setRole(r)}catch(e:any){alert(e.message)}}}>{role==='worker'?'💼 عميل':'👷 عامل'}</button></div></header>{err&&<div className="alert">{err}</div>}<section className="content">
 {tab==='home'&&<Home data={data} role={role} go={setTab}/>} {tab==='tasks'&&<Tasks data={data} reload={()=>load('tasks')}/>} {tab==='my'&&<MyTasks data={data} reload={()=>load('my')}/>} {tab==='invite'&&<Invite data={data}/>} {tab==='wallet'&&<Wallet data={data} reload={()=>load('wallet')}/>} {tab==='post'&&<Post onDone={()=>setTab('posts')}/>} {tab==='posts'&&<Posts data={data} reload={()=>load('posts')}/>} {tab==='deposits'&&<Deposits data={data} reload={()=>load('deposits')}/>} {tab==='notifications'&&<Notifications data={data} reload={()=>load('notifications')}/>} {tab==='admin'&&isAdmin&&<Admin data={data} reload={()=>load('admin')}/>} </section><nav className="bottom">{nav.map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</nav></main>
}

function Home({data,role,go}:any){
 const [adBusy,setAdBusy]=useState(false); const ads=data.ads||{completed:0,limit:5};
 async function ad(){if(adBusy||ads.completed>=ads.limit)return;setAdBusy(true);try{const c=window.Adsgram?.init({blockId:process.env.NEXT_PUBLIC_ADSGRAM_BLOCK_ID});if(!c)throw new Error('إعلانات AdsGram غير جاهزة');const result=await c.show();if(!result?.done)throw new Error('لم يكتمل الإعلان');alert('تمت مشاهدة الإعلان. سيتم تأكيد المكافأة من AdsGram.');setTimeout(()=>location.reload(),3500)}catch(e:any){alert(e.message||'تعذر عرض الإعلان')}finally{setAdBusy(false)}}
 return <div className="stack"><div className="hero"><div className="logo">S</div><div><p className="muted">أهلاً بك 👋</p><h1>{role==='worker'?'ابدأ الكسب اليوم':'أنشئ عملاً واحصل على نتيجة'}</h1><p className="muted">منصة Sera Time للأعمال والمكافآت.</p></div></div><div className="grid"><Stat t="الرصيد المتاح" v={money(data.wallet?.available)}/><Stat t={role==='worker'?'إجمالي الأرباح':'إجمالي الإنفاق'} v={money(role==='worker'?data.wallet?.earned:data.wallet?.spent)}/><Stat t="الأعمال المكتملة" v={data.completed||0}/><Stat t="إحالاتك" v={money(data.referralEarned)}/></div>{role==='worker'&&<div className="card adcard"><div><b>📺 شاهد الإعلانات</b><p className="muted">1 ETB لكل إعلان • {ads.completed}/{ads.limit} اليوم</p></div><button disabled={adBusy||ads.completed>=ads.limit} onClick={ad}>{adBusy?'جاري العرض...':'مشاهدة إعلان'}</button></div>}<div className="quick"><button onClick={()=>go(role==='worker'?'tasks':'post')}>{role==='worker'?'📋 تصفح الأعمال':'➕ نشر عمل'}</button><button onClick={()=>go('wallet')}>💰 المحفظة</button><button onClick={()=>go('notifications')}>🔔 الإشعارات</button></div></div>
}
function Stat({t,v}:any){return <div className="card stat"><span>{t}</span><b>{v}</b></div>}
function Tasks({data,reload}:any){const [cat,setCat]=useState('');const ts=(data.tasks||[]).filter((x:any)=>!cat||x.category===cat);const cats=[...new Set((data.tasks||[]).map((x:any)=>x.category).filter(Boolean))] as string[];return <div className="stack"><h2>الأعمال المتاحة</h2><div className="chips"><button onClick={()=>setCat('')}>الكل</button>{cats.map(c=><button key={c} onClick={()=>setCat(c)}>{c}</button>)}</div>{ts.map((t:any)=><div className="card task" key={t.id}><div className="grow"><div className="row"><b>{t.title}</b><span className="badge">{t.category}</span></div><p>{t.description}</p><small>المهلة: {Number(t.deadline_hours||0).toFixed(1)} ساعة</small></div><div className="right"><strong>{money(t.worker_reward)}</strong><button onClick={async()=>{try{await api('accept-task',{taskId:t.id});reload()}catch(e:any){alert(e.message)}}}>قبول</button></div></div>)}{!ts.length&&<Empty text="لا توجد أعمال متاحة الآن"/>}</div>}
function MyTasks({data,reload}:any){const [content,setContent]=useState('');return <div className="stack"><h2>مهامي</h2>{(data.tasks||[]).map((t:any)=><div className="card taskCard" key={t.id}><div className="row"><b>{t.title}</b><span className="badge">{t.status_am}</span></div><p>{t.description}</p><small>آخر موعد: {new Date(t.deadline_at).toLocaleString('am-ET')}</small>{['assigned','revision_requested'].includes(t.status)&&<div className="form"><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="رابط العمل أو تفاصيل التسليم"/><input type="file" multiple/><button onClick={async()=>{try{await api('submit-task',{taskId:t.id,content});setContent('');reload()}catch(e:any){alert(e.message)}}}>إرسال للتقييم</button></div>}</div>)}{!data.tasks?.length&&<Empty text="ليس لديك عمل نشط"/>}</div>}
function Invite({data}:any){return <div className="stack"><h2>دعوة الأصدقاء</h2><div className="card"><h3>اربح من الإحالات</h3><p className="muted">5% من أرباح العامل المُحال بعد إكمال العمل، وفق قواعد المنصة.</p><div className="invite">{data.link||'جاري التحميل...'}</div><button onClick={()=>navigator.clipboard?.writeText(data.link||'')}>نسخ رابط الدعوة</button></div><div className="grid"><Stat t="الإحالات" v={data.count||0}/><Stat t="الأرباح" v={money(data.earned)}/></div></div>}
function Wallet({data,reload}:any){const [amount,setAmount]=useState(''),[method,setMethod]=useState('telebirr'),[acct,setAcct]=useState(''),[name,setName]=useState('');return <div className="stack"><h2>المحفظة</h2><div className="hero"><div><span className="muted">الرصيد المتاح</span><h1>{money(data.available)}</h1><small className="muted">محجوز: {money(data.reserved)}</small></div></div><div className="card form"><h3>سحب الأموال</h3><p className="muted">الحد الأدنى: {money(data.minWithdrawal)}</p><input type="number" min="1000" placeholder="المبلغ" value={amount} onChange={e=>setAmount(e.target.value)}/><select value={method} onChange={e=>setMethod(e.target.value)}><option value="telebirr">Telebirr</option><option value="bank">بنك إثيوبي</option></select><input placeholder="رقم Telebirr / رقم الحساب" value={acct} onChange={e=>setAcct(e.target.value)}/><input placeholder="الاسم الكامل" value={name} onChange={e=>setName(e.target.value)}/><button onClick={async()=>{try{await api('withdraw',{amount:Number(amount),method,accountNumber:acct,accountName:name});alert('تم إرسال طلب السحب');reload()}catch(e:any){alert(e.message)}}}>إرسال طلب السحب</button></div><div className="card"><h3>سجل المعاملات</h3>{(data.transactions||[]).map((x:any)=><div className="history" key={x.id}><span>{x.description||x.type}</span><b>{money(x.amount)}</b></div>)}</div></div>}
function Post({onDone}:any){const [f,setF]=useState<any>({category:'Programming',title:'',description:'',requirements:'',deadlineHours:24,budget:''});return <div className="stack"><h2>نشر عمل</h2><div className="card form"><select value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{['Graphic Design','Logo Design','Video Editing','Photo Editing','Writing','Translation','Data Entry','Voice Over','Social Media','Programming','Website Development','AI Services','Marketing','Research','Excel'].map(x=><option key={x}>{x}</option>)}</select><input placeholder="عنوان العمل" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><textarea placeholder="وصف دقيق للعمل" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><textarea placeholder="المتطلبات والتعليمات" value={f.requirements} onChange={e=>setF({...f,requirements:e.target.value})}/><input type="number" min="1" placeholder="الميزانية الإجمالية ETB" value={f.budget} onChange={e=>setF({...f,budget:e.target.value})}/><input type="number" min="1" placeholder="المهلة بالساعات" value={f.deadlineHours} onChange={e=>setF({...f,deadlineHours:Number(e.target.value)})}/><input type="file" multiple/><div className="notice">سيتم حجز ميزانية العمل عند النشر. رسوم المنصة الافتراضية 10%.</div><button onClick={async()=>{try{await api('create-task',f);alert('تم نشر العمل');onDone()}catch(e:any){alert(e.message)}}}>نشر العمل</button></div></div>}
function Posts({data,reload}:any){return <div className="stack"><h2>أعمالي المنشورة</h2>{(data.tasks||[]).map((t:any)=><ClientTask key={t.id} t={t} reload={reload}/>)}{!data.tasks?.length&&<Empty text="لم تنشر أعمالاً بعد"/>}</div>}
function ClientTask({t,reload}:any){const [reason,setReason]=useState('');return <div className="card taskCard"><div className="row"><b>{t.title}</b><span className="badge">{t.status_am||t.status}</span></div><p>{t.description}</p><div className="row"><strong>{money(t.budget)}</strong><small>{t.category}</small></div>{t.status==='submitted'&&<div className="actions"><button onClick={async()=>{try{await api('approve-task',{taskId:t.id});reload()}catch(e:any){alert(e.message)}}}>✅ قبول ودفع</button><input placeholder="سبب التعديل" value={reason} onChange={e=>setReason(e.target.value)}/><button onClick={async()=>{try{await api('request-revision',{taskId:t.id,reason});reload()}catch(e:any){alert(e.message)}}}>🔁 طلب تعديل</button><button className="danger" onClick={async()=>{try{await api('open-dispute',{taskId:t.id,reason:reason||'أحتاج مراجعة الإدارة'});reload()}catch(e:any){alert(e.message)}}}>⚖️ نزاع</button></div>}</div>}
function Deposits({data,reload}:any){const [amount,setAmount]=useState(''),[method,setMethod]=useState('telebirr'),[ref,setRef]=useState('');return <div className="stack"><h2>إيداع رصيد</h2><div className="card"><p>أرسل المبلغ عبر وسيلة الدفع الرسمية ثم أدخل المرجع أدناه. الحد الأدنى الافتراضي {money(data.minDeposit)}.</p><p className="notice">قناة الإيداع: <a href="https://t.me/depistseratime">@depistseratime</a></p><div className="form"><input type="number" placeholder="المبلغ ETB" value={amount} onChange={e=>setAmount(e.target.value)}/><select value={method} onChange={e=>setMethod(e.target.value)}><option value="telebirr">Telebirr</option><option value="bank">بنك</option></select><input placeholder="رقم المرجع / Transaction ID" value={ref} onChange={e=>setRef(e.target.value)}/><input type="file"/><button onClick={async()=>{try{await api('create-deposit',{amount:Number(amount),method,reference:ref});alert('تم إرسال طلب الإيداع للمراجعة');reload()}catch(e:any){alert(e.message)}}}>إرسال طلب الإيداع</button></div></div><div className="card">{(data.deposits||[]).map((x:any)=><div className="history" key={x.id}><span>{money(x.amount)} · {x.method}</span><b>{x.status_am||x.status}</b></div>)}</div></div>}
function Notifications({data,reload}:any){return <div className="stack"><h2>الإشعارات</h2>{(data.notifications||[]).map((n:any)=><div className="card" key={n.id}><b>{n.title}</b><p>{n.body}</p><small className="muted">{new Date(n.created_at).toLocaleString('am-ET')}</small></div>)}{!data.notifications?.length&&<Empty text="لا توجد إشعارات"/>}<button onClick={async()=>{await api('read-notifications');reload()}}>تحديد الكل كمقروء</button></div>}
function Admin({data,reload}:any){return <div className="stack"><h2>لوحة الإدارة</h2><div className="grid"><Stat t="المستخدمون" v={data.users||0}/><Stat t="الأعمال" v={data.tasks||0}/><Stat t="سحب معلق" v={data.pendingWithdrawals||0}/><Stat t="نزاعات" v={data.disputes||0}/></div><div className="card"><h3>طلبات السحب</h3>{(data.withdrawals||[]).map((w:any)=><div className="adminRow" key={w.id}><div><b>{money(w.amount)}</b><small>{w.method} · {w.account_name} · {w.account_number}</small></div><div className="actions"><button onClick={async()=>{await api('admin-withdraw',{withdrawalId:w.id,status:'paid'});reload()}}>دفع</button><button className="danger" onClick={async()=>{await api('admin-withdraw',{withdrawalId:w.id,status:'rejected',reason:'تم رفض الطلب بعد المراجعة'});reload()}}>رفض</button></div></div>)}</div><div className="card"><h3>طلبات الإيداع</h3>{(data.deposits||[]).map((d:any)=><div className="adminRow" key={d.id}><span>{money(d.amount)} · {d.method} · {d.reference}</span><div className="actions"><button onClick={async()=>{await api('admin-deposit',{depositId:d.id,status:'approved'});reload()}}>قبول</button><button className="danger" onClick={async()=>{await api('admin-deposit',{depositId:d.id,status:'rejected',reason:'غير معتمد'});reload()}}>رفض</button></div></div>)}</div></div>}
function Empty({text}:any){return <div className="card center muted">{text}</div>}
