"use client";

import { useEffect, useMemo, useState } from "react";

declare global { interface Window { Telegram?: { WebApp?: any }; Adsgram?: any } }

type Role = "worker" | "client";
type Tab = "home" | "tasks" | "my" | "invite" | "wallet" | "post" | "posts" | "deposits" | "notifications" | "admin";

const CATEGORIES = [
  ["graphic_design","🎨 ግራፊክ ዲዛይን"],["logo_design","✨ ሎጎ ዲዛይን"],["video_editing","🎬 ቪዲዮ ኤዲቲንግ"],["photo_editing","📸 ፎቶ ኤዲቲንግ"],["writing","✍️ ጽሑፍ"],["translation","🌐 ትርጉም"],["data_entry","⌨️ ዳታ ኤንትሪ"],["voice_over","🎙️ ቮይስ ኦቨር"],["social_media","📱 ሶሻል ሚዲያ"],["programming","💻 ፕሮግራሚንግ"],["website_development","🌍 ዌብሳይት"],["ai_services","🤖 AI አገልግሎት"],["marketing","📣 ማርኬቲንግ"],["research","🔎 ምርምር"],["excel","📊 Excel"]
];
const catLabel=(x:string)=>CATEGORIES.find(([k])=>k===x)?.[1]||x;
const money=(v:any)=>`${Number(v||0).toFixed(2)} ETB`;

async function api(action:string, body:any={}){
  const initData=window.Telegram?.WebApp?.initData||"";
  const ref=new URLSearchParams(window.location.search).get("ref")||"";
  const r=await fetch(`/api/${action}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,initData,ref})});
  const d=await r.json().catch(()=>({error:"Server returned invalid response"}));
  if(!r.ok) throw new Error(d.error||"አንድ ችግር ተፈጥሯል");
  return d;
}

export default function App(){
  const [me,setMe]=useState<any>(null),[role,setRole]=useState<Role>("worker"),[tab,setTab]=useState<Tab>("home"),[data,setData]=useState<any>({}),[error,setError]=useState(""),[loading,setLoading]=useState(true),[onboard,setOnboard]=useState(false);
  const loadMe=async()=>{try{const x=await api("me");setMe(x.user);const saved=localStorage.getItem("sera_role");if(saved==="worker"||saved==="client")setRole(saved);else setOnboard(true)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
  const chooseRole=async(r:Role)=>{try{await api("set-role",{role:r});setRole(r);localStorage.setItem("sera_role",r);setOnboard(false);setTab("home")}catch(e:any){setError(e.message)}};
  const load=async(t:Tab=tab)=>{if(!me)return;setError("");try{let x:any={};if(t==="home")x=await api("dashboard",{role});else if(t==="tasks")x=await api("tasks");else if(t==="my")x=await api("my-tasks");else if(t==="invite")x=await api("referrals");else if(t==="wallet")x=await api("wallet");else if(t==="posts")x=await api("my-posts");else if(t==="deposits")x=await api("deposits");else if(t==="notifications")x=await api("notifications");else if(t==="admin")x=await api("admin-dashboard");setData(x)}catch(e:any){setError(e.message)}};
  useEffect(()=>{window.Telegram?.WebApp?.ready?.();window.Telegram?.WebApp?.expand?.();loadMe()},[]);
  useEffect(()=>{if(me&&!onboard)load(tab)},[me,role,tab,onboard]);
  if(loading)return <main className="app"><div className="splash"><div className="mark">S</div><h1>SERA TIME</h1><p>እባክዎ ትንሽ ይጠብቁ…</p></div></main>;
  if(error&&!me)return <main className="app"><div className="splash"><div className="mark">S</div><h1>SERA TIME</h1><div className="error">{error}</div></div></main>;
  if(onboard)return <RolePicker choose={chooseRole} name={me?.first_name||""}/>;
  const isAdmin=!!me?.is_admin;
  const nav: [Tab,string,string][] = role==="worker" ? [["home","⌂","ዋና"],["tasks","◈","ስራዎች"],["my","✓","የእኔ"],["invite","♧","ግብዣ"],["wallet","◉","ዋሌት"]] : [["home","⌂","ዋና"],["post","＋","ስራ ለጥፍ"],["posts","▣","ልጥፎች"],["deposits","＋","አስገባ"],["wallet","◉","ዋሌት"]];
  return <main className="app"><header className="header"><div className="brand"><div className="mini">S</div><div><strong>SERA TIME</strong><span>ስራ • ገቢ • እድል</span></div></div><div className="headActions"><button className="circle" onClick={()=>setTab("notifications")}>♧</button><button className="roleBtn" onClick={()=>setOnboard(true)}>{role==="worker"?"💼 ደንበኛ":"👷 ሰራተኛ"}</button></div></header>{error&&<div className="error topError">{error}<button onClick={()=>setError("")}>×</button></div>}<section className="content">{tab==="home"&&<Home data={data} role={role} go={setTab}/>} {tab==="tasks"&&<Tasks data={data} reload={()=>load("tasks")}/>} {tab==="my"&&<MyTasks data={data} reload={()=>load("my")}/>} {tab==="invite"&&<Invite data={data}/>} {tab==="wallet"&&<Wallet data={data} reload={()=>load("wallet")}/>} {tab==="post"&&<Post onDone={()=>{setTab("posts");load("posts")}}/>} {tab==="posts"&&<Posts data={data} reload={()=>load("posts")}/>} {tab==="deposits"&&<Deposits data={data} reload={()=>load("deposits")}/>} {tab==="notifications"&&<Notifications data={data} reload={()=>load("notifications")}/>} {tab==="admin"&&isAdmin&&<Admin data={data} reload={()=>load("admin")}/>}</section><nav className="bottom">{nav.map(([id,icon,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><span>{icon}</span>{label}</button>)}{isAdmin&&<button className={tab==="admin"?"active":""} onClick={()=>setTab("admin")}><span>⚙</span>አስተዳደር</button>}</nav></main>;
}

function RolePicker({choose,name}:{choose:(r:Role)=>void,name:string}){return <main className="app picker"><div className="pickerInner"><div className="mark big">S</div><div className="eyebrow">እንኳን ወደ Sera Time በደህና መጡ 👋</div><h1>{name?`${name}፣ እንኳን ደህና መጡ`:`የሚፈልጉትን ይምረጡ`}</h1><p className="muted centerText">Sera Time ላይ ስራ መስራት ወይም ስራ ማስተናገድ ይችላሉ።</p><div className="roleCards"><button onClick={()=>choose("worker")}><span>👷</span><b>ሰራተኛ</b><small>ስራዎችን ይቀበሉ፣ ይስሩ እና ይክፈሉ</small></button><button onClick={()=>choose("client")}><span>💼</span><b>ደንበኛ</b><small>ስራ ይለጥፉ እና ሰራተኛ ያግኙ</small></button></div><p className="tiny">እንደፈለጉ ሚናዎን በኋላ መቀየር ይችላሉ።</p></div></main>}

function Home({data,role,go}:any){const [adBusy,setAdBusy]=useState(false);const ads=data.ads||{completed:0,limit:5};const showAd=async()=>{if(adBusy||ads.completed>=ads.limit)return;setAdBusy(true);try{const c=window.Adsgram?.init({blockId:process.env.NEXT_PUBLIC_ADSGRAM_BLOCK_ID});if(!c)throw new Error("AdsGram አልተዘጋጀም");const r=await c.show();if(!r?.done)throw new Error("ማስታወቂያው አልተጠናቀቀም");setTimeout(()=>location.reload(),2500)}catch(e:any){alert(e.message)}finally{setAdBusy(false)}};return <div className="stack"><div className="hero"><div className="heroGlow"/><div className="heroMark">S</div><div><div className="eyebrow">{role==="worker"?"የስራ መድረክ":"የስራ ማስተናገጃ መድረክ"}</div><h1>{role==="worker"?"ስራ ይስሩ፣ ገቢ ያግኙ":"ስራዎን ይለጥፉ፣ ውጤት ያግኙ"}</h1><p>በSera Time በቀላሉ ይጀምሩ።</p></div></div><div className="statGrid"><Stat icon="◉" label="ያለዎት ሂሳብ" value={money(data.wallet?.available)}/><Stat icon={role==="worker"?"↗":"↘"} label={role==="worker"?"ጠቅላላ ገቢ":"ጠቅላላ ወጪ"} value={money(role==="worker"?data.wallet?.earned:data.wallet?.spent)}/><Stat icon="✓" label="የተጠናቀቁ" value={data.completed||0}/><Stat icon="♧" label="ሪፈራል" value={money(data.referralEarned)}/></div>{role==="worker"&&<div className="adCard"><div><b>🎁 ተጨማሪ ገቢ</b><span>ማስታወቂያ ይመልከቱ • 1 ETB • {ads.completed}/{ads.limit}</span></div><button disabled={adBusy||ads.completed>=ads.limit} onClick={showAd}>{adBusy?"እየተጫነ…":"ይመልከቱ"}</button></div>}<div className="sectionHead"><h2>{role==="worker"?"ፈጣን መጀመሪያ":"የፈጣን እርምጃ"}</h2></div><div className="quickGrid"><button onClick={()=>go(role==="worker"?"tasks":"post")}><span>{role==="worker"?"◈":"＋"}</span>{role==="worker"?"ስራዎችን ይመልከቱ":"ስራ ይለጥፉ"}</button><button onClick={()=>go("wallet")}><span>◉</span>ዋሌት</button><button onClick={()=>go("notifications")}><span>♧</span>ማሳወቂያ</button></div></div>}
function Stat({icon,label,value}:{icon:string,label:string,value:any}){return <div className="stat"><span className="statIcon">{icon}</span><span className="statLabel">{label}</span><b>{value}</b></div>}
function Tasks({data,reload}:any){const [cat,setCat]=useState("");const ts=(data.tasks||[]).filter((x:any)=>!cat||x.category===cat);const cats=[...new Set((data.tasks||[]).map((x:any)=>x.category).filter(Boolean))] as string[];return <div className="stack"><PageTitle title="ስራዎች" sub="ለመቀበል ዝግጁ የሆኑ ስራዎች"/><div className="chips"><button className={!cat?"selected":""} onClick={()=>setCat("")}>ሁሉም</button>{cats.map(c=><button className={cat===c?"selected":""} key={c} onClick={()=>setCat(c)}>{catLabel(c)}</button>)}</div>{ts.map((t:any)=><div className="taskCard" key={t.id}><div className="taskTop"><span className="badge">{catLabel(t.category)}</span><strong>{money(t.worker_reward)}</strong></div><h3>{t.title}</h3><p>{t.description}</p><div className="taskMeta"><span>⏱ {new Date(t.deadline_at).toLocaleString("am-ET")}</span><button onClick={async()=>{try{await api("accept-task",{taskId:t.id});reload()}catch(e:any){alert(e.message)}}}>ስራውን ተቀበል</button></div></div>)}{!ts.length&&<Empty text="አሁን ላይ የሚገኝ ስራ የለም"/>}</div>}
function MyTasks({data,reload}:any){return <div className="stack"><PageTitle title="የእኔ ስራዎች" sub="የተቀበሏቸውን ስራዎች እዚህ ይከታተሉ"/>{(data.tasks||[]).map((t:any)=><TaskSubmission key={t.id} t={t} reload={reload}/>)}{!data.tasks?.length&&<Empty text="እስካሁን ስራ አልተቀበሉም"/>}</div>}
function TaskSubmission({t,reload}:any){const [content,setContent]=useState("");const can=["assigned","revision_requested"].includes(t.status);return <div className="taskCard"><div className="taskTop"><span className="badge">{t.status==="revision_requested"?"ማሻሻያ ተጠይቋል":t.status==="submitted"?"ተልኳል":"በሂደት ላይ"}</span><strong>{money(t.worker_reward)}</strong></div><h3>{t.title}</h3><p>{t.description}</p><div className="taskMeta"><span>የመጨረሻ ቀን: {new Date(t.deadline_at).toLocaleString("am-ET")}</span></div>{can&&<div className="form"><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="የሰሩትን ስራ ወይም የፋይል ማገናኛ ያስገቡ"/><button onClick={async()=>{try{await api("submit-task",{taskId:t.id,content});setContent("");reload()}catch(e:any){alert(e.message)}}}>ስራውን ላክ</button></div>}</div>}
function Invite({data}:any){return <div className="stack"><PageTitle title="ግብዣ" sub="ጓደኞችዎን ይጋብዙ እና 5% ሪፈራል ገቢ ያግኙ"/><div className="inviteHero"><span>♧</span><b>የግብዣ ሊንክዎ</b><p>የተጋበዙት ሰራተኛ ስራ ካጠናቀቀ ከሚያገኘው የስራ ገቢ 5% ያገኛሉ።</p><div className="inviteLink">{data.link||"-"}</div><button onClick={()=>navigator.clipboard?.writeText(data.link||"")}>ሊንኩን ቅዳ</button></div><div className="statGrid two"><Stat icon="♧" label="የተጋበዙ" value={data.count||0}/><Stat icon="◉" label="የሪፈራል ገቢ" value={money(data.earned)}/></div></div>}
function Wallet({data,reload}:any){const [amount,setAmount]=useState(""),[method,setMethod]=useState("telebirr"),[acct,setAcct]=useState(""),[name,setName]=useState("");return <div className="stack"><PageTitle title="ዋሌት" sub="የETB ገንዘብዎን ይቆጣጠሩ"/><div className="balance"><span>ያለዎት ቀሪ ሂሳብ</span><strong>{money(data.available)}</strong><small>የተያዘ: {money(data.reserved)}</small></div><div className="form card"><h3>ገንዘብ ማውጣት</h3><p className="muted">ዝቅተኛ ማውጫ: {money(data.minWithdrawal??1000)}</p><input type="number" min="1000" placeholder="የሚያወጡት መጠን" value={amount} onChange={e=>setAmount(e.target.value)}/><select value={method} onChange={e=>setMethod(e.target.value)}><option value="telebirr">Telebirr</option><option value="bank">የኢትዮጵያ ባንክ</option></select><input placeholder="የሂሳብ / Telebirr ቁጥር" value={acct} onChange={e=>setAcct(e.target.value)}/><input placeholder="ሙሉ ስም" value={name} onChange={e=>setName(e.target.value)}/><button onClick={async()=>{try{await api("withdraw",{amount:Number(amount),method,accountNumber:acct,accountName:name});alert("የማውጣት ጥያቄዎ ተልኳል");setAmount("");reload()}catch(e:any){alert(e.message)}}}>የማውጣት ጥያቄ ላክ</button></div><div className="card"><h3>የግብይት ታሪክ</h3>{(data.transactions||[]).map((x:any)=><div className="history" key={x.id}><span>{x.description||x.type}</span><b>{money(x.amount)}</b></div>)}{!data.transactions?.length&&<p className="muted">እስካሁን ግብይት የለም።</p>}</div></div>}
function Post({onDone}:{onDone:()=>void}){const [f,setF]=useState<any>({category:CATEGORIES[0][0],title:"",description:"",requirements:"",deadlineHours:24,budget:""}),[busy,setBusy]=useState(false);const set=(k:string,v:any)=>setF({...f,[k]:v});return <div className="stack"><PageTitle title="ስራ ለጥፍ" sub="ለሰራተኞች ግልጽ መመሪያ ይስጡ"/><div className="form card"><label>ምድብ<select value={f.category} onChange={e=>set("category",e.target.value)}>{CATEGORIES.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>የስራ ርዕስ<input value={f.title} onChange={e=>set("title",e.target.value)} placeholder="ምሳሌ፦ ሎጎ ዲዛይን እፈልጋለሁ"/></label><label>ዝርዝር መግለጫ<textarea value={f.description} onChange={e=>set("description",e.target.value)} placeholder="ስራው በትክክል ምን ይፈልጋል?"/></label><label>መስፈርቶች / መመሪያ<textarea value={f.requirements} onChange={e=>set("requirements",e.target.value)} placeholder="የሚፈለጉ ፋይሎች፣ መጠን፣ ቅርጽ…"/></label><div className="twoFields"><label>የስራ ጊዜ (ሰዓት)<input type="number" min="1" value={f.deadlineHours} onChange={e=>set("deadlineHours",e.target.value)}/></label><label>በጀት (ETB)<input type="number" min="1" value={f.budget} onChange={e=>set("budget",e.target.value)} placeholder="100"/></label></div><div className="feeBox"><span>ሰራተኛ የሚያገኘው</span><b>{money(Number(f.budget||0)*.9)}</b><small>10% የመድረክ ክፍያ ይቀነሳል።</small></div><button disabled={busy} onClick={async()=>{try{setBusy(true);await api("create-task",{...f,budget:Number(f.budget)});alert("ስራው ተለጥፏል");onDone()}catch(e:any){alert(e.message)}finally{setBusy(false)}}}>{busy?"እየተለጠፈ…":"ስራውን ለጥፍ"}</button></div></div>}
function Posts({data,reload}:any){return <div className="stack"><PageTitle title="የእኔ ልጥፎች" sub="የለጠፏቸውን ስራዎች ይከታተሉ"/>{(data.tasks||[]).map((t:any)=><ClientTask key={t.id} t={t} reload={reload}/>)}{!data.tasks?.length&&<Empty text="እስካሁን ስራ አልለጠፉም"/>}</div>}
function ClientTask({t,reload}:any){return <div className="taskCard"><div className="taskTop"><span className="badge">{t.status}</span><strong>{money(t.budget)}</strong></div><h3>{t.title}</h3><p>{t.description}</p>{t.status==="submitted"&&<div className="actions"><button onClick={async()=>{try{await api("approve-task",{taskId:t.id});reload()}catch(e:any){alert(e.message)}}}>✓ ስራውን አጽድቅ</button><button className="secondary" onClick={async()=>{const reason=prompt("የማሻሻያ ምክንያት");if(!reason)return;try{await api("request-revision",{taskId:t.id,reason});reload()}catch(e:any){alert(e.message)}}}>↻ ማሻሻያ ጠይቅ</button><button className="danger" onClick={async()=>{const reason=prompt("የክርክር ምክንያት");if(!reason)return;try{await api("open-dispute",{taskId:t.id,reason});reload()}catch(e:any){alert(e.message)}}}>⚖ ክርክር</button></div>}</div>}
function Deposits({data,reload}:any){const [amount,setAmount]=useState(""),[method,setMethod]=useState("telebirr"),[reference,setReference]=useState("");return <div className="stack"><PageTitle title="ገንዘብ አስገባ" sub="በኦፊሴላዊ የክፍያ መመሪያ መሠረት ይክፈሉ"/><div className="depositInfo"><b>የክፍያ ቻናል</b><a href="https://t.me/depistseratime" target="_blank">@depistseratime ↗</a><p>ክፍያዎን ከፈጸሙ በኋላ የማጣቀሻ ቁጥሩን ያስገቡ።</p></div><div className="form card"><label>መጠን (ETB)<input type="number" min="100" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>ዘዴ<select value={method} onChange={e=>setMethod(e.target.value)}><option value="telebirr">Telebirr</option><option value="bank">ባንክ</option></select></label><label>የክፍያ ማጣቀሻ<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Reference / Transaction ID"/></label><button onClick={async()=>{try{await api("create-deposit",{amount:Number(amount),method,reference});alert("የኢዲፖዚት ጥያቄዎ ተልኳል");setAmount("");setReference("");reload()}catch(e:any){alert(e.message)}}}>ማስገባት ላክ</button></div><div className="card"><h3>የኢዲፖዚት ታሪክ</h3>{(data.deposits||[]).map((d:any)=><div className="history" key={d.id}><span>{d.method} · {d.status}</span><b>{money(d.amount)}</b></div>)}{!data.deposits?.length&&<p className="muted">ምንም የኢዲፖዚት ጥያቄ የለም።</p>}</div></div>}
function Notifications({data,reload}:any){return <div className="stack"><PageTitle title="ማሳወቂያዎች" sub="የSera Time እንቅስቃሴዎች"/><button onClick={async()=>{await api("read-notifications");reload()}}>ሁሉንም እንደተነበበ ምልክት አድርግ</button>{(data.notifications||data||[]).map((n:any)=><div className={`notice ${n.read_at?"read":""}`} key={n.id}><b>{n.title}</b><p>{n.body}</p><small>{new Date(n.created_at).toLocaleString("am-ET")}</small></div>)}{!(data.notifications||data||[]).length&&<Empty text="ማሳወቂያ የለም"/>}</div>}
function Admin({data,reload}:any){return <div className="stack"><PageTitle title="አስተዳደር" sub="የSera Time መድረክ አጠቃላይ ሁኔታ"/><div className="statGrid"><Stat icon="♙" label="ተጠቃሚዎች" value={data.users||0}/><Stat icon="◈" label="ስራዎች" value={data.tasks||0}/><Stat icon="＋" label="ኢዲፖዚቶች" value={data.pending_deposits||0}/><Stat icon="↗" label="ማውጫ" value={data.pending_withdrawals||0}/></div><div className="card"><h3>የማውጣት ጥያቄዎች</h3>{(data.withdrawals||[]).map((w:any)=><div className="adminRow" key={w.id}><div><b>{money(w.amount)}</b><small>{w.method} · {w.account_name} · {w.account_number}</small></div><div className="actions"><button onClick={async()=>{await api("admin-withdraw",{withdrawalId:w.id,status:"paid"});reload()}}>ክፈል</button><button className="danger" onClick={async()=>{await api("admin-withdraw",{withdrawalId:w.id,status:"rejected"});reload()}}>አትቀበል</button></div></div>)}{!(data.withdrawals||[]).length&&<p className="muted">የሚጠብቅ ማውጫ የለም።</p>}</div><div className="card"><h3>የኢዲፖዚት ጥያቄዎች</h3>{(data.deposits||[]).map((d:any)=><div className="adminRow" key={d.id}><div><b>{money(d.amount)}</b><small>{d.method} · {d.reference||"ማጣቀሻ የለም"}</small></div><div className="actions"><button onClick={async()=>{await api("admin-deposit",{depositId:d.id,status:"approved"});reload()}}>ቀበል</button><button className="danger" onClick={async()=>{await api("admin-deposit",{depositId:d.id,status:"rejected"});reload()}}>አትቀበል</button></div></div>)}{!(data.deposits||[]).length&&<p className="muted">የሚጠብቅ ኢዲፖዚት የለም።</p>}</div></div>}
function PageTitle({title,sub}:{title:string,sub:string}){return <div className="pageTitle"><h2>{title}</h2><p>{sub}</p></div>}
function Empty({text}:{text:string}){return <div className="empty"><span>○</span><b>{text}</b><small>እንደገና በኋላ ይመልከቱ።</small></div>}
